### ISSUE TITLE
大佬，你好

### ISSUE THREAD

**Issue by FlyaOoo** [moyuweiqing/dazhongdianping#1]
不知道是怎么解决登陆问题的，如果需要大量爬评论，是不是要自己准备大量账号

**Comment by moyuweiqing** [comment]
你可以先在大众点评上进行登录，记住账号密码之类的，登录完成之后刷新可以发现依然是已经登录的。这个时候你找到cookie复制过去作为header就行，一般来说一个cookie能用一段时间的，你可以试试
 &nbsp;
  
 华南理工大学&nbsp;South China University of Technology  软件学院 School of Software Engineering
 陈港鸿 Chen Ganghong


 &nbsp;
  

 

 ------------------&nbsp;原始邮件&nbsp;------------------
  发件人:&nbsp;"FlyaOoo"<notifications@github.com&gt;;
 发送时间:&nbsp;2020年4月11日(星期六) 下午2:04
 收件人:&nbsp;"moyuweiqing/dazhongdianping"<dazhongdianping@noreply.github.com&gt;;
 抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
 主题:&nbsp;[moyuweiqing/dazhongdianping] 大佬，你好 (#1)

 

 

 
不知道是怎么解决登陆问题的，如果需要大量爬评论，是不是要自己准备大量账号
